### ISSUE TITLE
Flicker when image clicked

### ISSUE THREAD

**Issue by aogaili** [gauravchl/react-image-story#2]
There is some flickering when an image is selected. I'm assuming it has to with this [line](https://github.com/gauravchl/react-smart-gallery/blob/master/src/index.jsx#L22). 

I'll take a closer look to confirm that this is the issue.

**Comment by gauravchl** [comment]
@aliogaili Yeah, i've also notice some flickering. Probably need to shallow compare the root component before rendering it when prop changes.

**Comment by aogaili** [comment]
@gauravchl yup, I've tested it locally and the flicker is gone once the force update line is removed when new props are received.

**Comment by gauravchl** [comment]
@aliogaili Flickering issues fixed in v0.1.0 🎉 
Let me know if you are still seeing it.

**Comment by aogaili** [comment]
Thanks @gauravchl  I'll test and confirm.

**Comment by aogaili** [comment]
I've tested it and the flicker is gone 👍
