### ISSUE TITLE
pass index to onImageSelect cb function 

### ISSUE THREAD

**Issue by aogaili** [gauravchl/react-image-story#4]
Currently the onImageSelect returns an event and src object however there might be a case where we've multiple images with the same src, therefore  it might be more accurate to pass back the index of the image clicked, what do you think?

**Comment by gauravchl** [comment]
@aliogaili That's great, we can pass index as a second argument. Will update it.

**Comment by gauravchl** [comment]
@aliogaili  Index is now available as a third argument @v0.1.2 🎉 🎉

**Comment by aogaili** [comment]
Thanks @gauravchl  :)
