### ISSUE TITLE
Manualy set images counter

### ISSUE THREAD

**Issue by zombopanda** [gauravchl/react-image-story#5]
Hello, I am using your component to display galleries with a lot of images. So now I pass images array like `['image1.jpg', 'image2.jpg', 'images3.png', 'images4.png', 'blank.jpg', 'blank.jpg',...]` as a workaround to prevent additional loading of images. It will be fine if I can optionally pass a number of images to display a  +N counter.

**Comment by gauravchl** [comment]
@zombopanda Currently it support maximum of 4 images to be displayed in any given layout. I've pushed a fix to v0.2.0 which will prevent unnecessary loading of extra images. You can now pass any number of images, it will load only upto first 4 images.

cheers!
