### ISSUE TITLE
React warning on force update

### ISSUE THREAD

**Issue by aogaili** [gauravchl/react-image-story#6]
If the component is mounted and unmounted quickly (user switching quickly between pages), react will throw the following error: 

`Warning: forceUpdate(...): Can only update a mounted or mounting component. This usually means you called forceUpdate() on an unmounted component. This is a no-op. Please check the code for the ImageStory component.`

As per[ react official page](https://facebook.github.io/react/blog/2015/12/16/ismounted-antipattern.html), an easy migration is maintain a state variable to check if the component is mounted before calling force update.

> An easy migration strategy for anyone upgrading their code to avoid isMounted() is to track the mounted status yourself. Just set a _isMounted property to true in componentDidMount and set it to false in componentWillUnmount, and use this variable to check your component's status.

**Comment by gauravchl** [comment]
@aliogaili Thanks for reporting this issue, it's fixed in latest release v0.2.0 https://github.com/gauravchl/react-smart-gallery/releases/tag/v0.2.0

**Comment by aogaili** [comment]
Great work @gauravchl ,  I can confirm all the warnings are gone now.
